services:
  nginx:
    image: nginx:1.25-alpine
    restart: always
    network_mode: host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media:/var/www/html/media
      - static:/var/www/html/admin/static
      - ./frontend/build/:/var/www/html
      - ./nginx/rizz-inst_online.crt:/etc/nginx/ssl/rizz-inst_online.crt
      - ./nginx/rizz-inst_online.key:/etc/nginx/ssl/rizz-inst_online.key
    depends_on:
      - server

  server:
    network_mode: host
    restart: unless-stopped
    build:
      context: ./backends/
      dockerfile: Dockerfile
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: drop_db
      SQL_HOST: 62.113.113.203
      SQL_USER: admin_user
      SQL_PASSWORD: Fos#83Fkladfq)
      SQL_PORT: 5432

    entrypoint: ./api.sh
    volumes:
      - static:/home/app/static
      - media:/home/app/media

volumes:
  media: {}
  static: {}
